[package]
name = "ballista-tui"
version = "0.0.1"
edition = "2024"

[dependencies]
chrono = "0.4.43"
color-eyre = "0.6.5"
crossterm = { version = "0.29.0", features = ["event-stream"] }
csv = "1.4.0"
dirs = "6.0"
futures = "0.3.31"
rand = "0.9.2"
ratatui = "0.30.0"
reqwest = { version = "0.13.1", features = ["json"] }
rust_decimal = "1.40.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
tokio-tungstenite = "0.28.0"
yahoo_finance_api = "4.1.0"

[workspace]
